# -*- coding: utf-8 -*-
"""Analise_metricas (1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gG6YheQjNC5mRPZW8szrj1oUqZMSpftr

# Instalação das bibliotecas
"""

!pip install utilsforecast

!pip install dataframe_image

!apt-get install chromium-chromedriver
!pip install dataframe_image

#Carrega as funções
import matplotlib.pyplot as plt
import matplotlib.cm as cm
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import dataframe_image as dfi
import nest_asyncio
from google.colab import files
from utilsforecast.losses import mae, mape,rmse,smape
from utilsforecast.evaluation import evaluate
from utilsforecast.plotting import plot_series
from google.colab import drive

"""## Fazer o upload do arquivo:

> avaliacao_modelos.csv


"""

# Upload dos arquivos
uploaded = files.upload()

# Leitura do conjunto de dados
df_metricas = pd.read_csv("avaliacao_modelos.csv")

""" Métricas que foram estimadas nos scripts LSTM_final_revisado.ipynb e SARIMA.ipynb, respectivamente."""

# Dados da tabela de métricas LSTM e SARIMA.
data = {
    'LSTM': [0.140, 0.0531, 0.167, 0.0537],
    'SARIMA':[0.49, 0.55, 0.1811, 0.1616]}

"""Criando um Data Frame para as métricas LSTM e SARIMA"""

# Criar o DataFrame
df = pd.DataFrame(data)

"""Concatenando a tabela de métricas dos modelos com as métricas LSTM e SARIMA"""

# Exibir o DataFrame
df_metricas['LSTM'] = df['LSTM']
df_metricas['Sarima'] = df['SARIMA']
df_total = df_metricas
display(df_total)

"""Gerando o gráfico de barras com as métricas MAE, MAPE, RMSE e sMAPE dos modelos"""

# Filtra só as colunas de modelos
model_cols = ['naive', 'lgbm', 'lasso', 'lin_reg', 'ridge', 'knn', 'mlp', 'rf','LSTM','Sarima']

# Define cores padrão para os modelos
def gerar_cores(valores, palette='viridis'):
    norm = plt.Normalize(min(valores), max(valores))
    cmap = cm.get_cmap(palette)
    return [cmap(norm(v)) for v in valores]

metricas = ['mae', 'mape', 'rmse', 'smape']
mae_row = df_total[df_total['metric'] == 'mae']
valores = mae_row[model_cols].values.flatten()

cores = gerar_cores(valores, palette='plasma')


# Cria uma figura com subplots por métrica
fig, axes = plt.subplots(2, 2, figsize=(14, 10))
axes = axes.flatten()

# Lista de métricas na ordem esperada
metricas = ['mae', 'mape', 'rmse', 'smape']

for i, metrica in enumerate(metricas):
    ax = axes[i]

    # Seleciona a linha da métrica
    linha = df_total[df_total['metric'] == metrica]

    # Extrai os valores dos modelos
    valores = linha[model_cols].values.flatten()

    # Creates colors based on the values of the current metric
    cores = gerar_cores(valores, palette='plasma')


    # Cria o gráfico de barras
    bars = ax.bar(model_cols, valores, color=cores)
    #ax.bar(model_cols, valores, color=cores)
    ax.set_title(f'{metrica.upper()} por modelo')
    ax.set_ylabel(metrica.upper())
    ax.set_xticklabels(model_cols, rotation=45)
    ax.bar_label(bars, fmt='%.2f', padding=3)
    ax.grid(axis='y', linestyle='--', alpha=0.5)

plt.suptitle('Comparação de Métricas de Erro entre Modelos', fontsize=16)
plt.tight_layout(rect=[0, 0, 1, 0.96])
plt.show()

"""Gerando uma tabela com gradiente das métricas de desempenho"""

df_total.style.background_gradient(cmap='RdYlGn_r', axis=1)

"""Criação de uma imagem com a tabela acima"""

nest_asyncio.apply()

styled_df = df_total.style.background_gradient(cmap='RdYlGn_r', axis=1)

dfi.export(styled_df, "tabela2.png", table_conversion='matplotlib')

