# -*- coding: utf-8 -*-
"""Demand.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/117dfG-Ye5WGvAzDGTAnhg49lavOFKH2r

# Instalação das bibliotecas
"""

# Instalando bibliotecas
!pip install prophet
!pip install -U mlforecast
!pip install -U utilsforecast
!pip show utilsforecast matplotlib pandas
!pip install statsmodels



#Carrega bibliotecas iniciais
import numpy as np
import pandas as pd
import seaborn as sns
from mlforecast import MLForecast
from mlforecast.target_transforms import Differences
from prophet import Prophet
from statsmodels.tsa.stattools import adfuller
from utilsforecast.losses import mae, mape,rmse,smape
from utilsforecast.evaluation import evaluate
import matplotlib.pyplot as plt
from utilsforecast.plotting import plot_series
from google.colab import files
import seaborn as sns
import lightgbm as lgb
from sklearn.base import BaseEstimator
from sklearn.linear_model import LinearRegression, Lasso, Ridge
from sklearn.neighbors import KNeighborsRegressor
from sklearn.neural_network import MLPRegressor
from sklearn.ensemble import RandomForestRegressor
from mlforecast.lag_transforms import ExpandingMean, RollingMean
from mlforecast.target_transforms import Differences
from google.colab import files
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
from mlforecast.utils import PredictionIntervals
sns.set()

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline

pd.plotting.register_matplotlib_converters()
plt.rc("figure", figsize=(10, 8))
plt.rc("font", size=10)

"""Fazer o upload do arquivo:


> base_de_dados_etanol.csv


"""

uploaded = files.upload()

"""# Dados

Utilizei os dados do CEPEA USP ESALQ - Preço do etanol (R$). Os valores estão em peridiocidade mensal, de Jan/2015 até Jun/2025.

Transformação dos dados
"""

# Função para carregar os dados do etanol
def carregar_dados_etanol():

    # Lista para armazenar dataframes (mantendo a lógica do código original)
    lista_dataframes = []

    # Lê o arquivo CSV
    df = pd.read_csv(
        "base_de_dados_etanol.csv",
        encoding='latin-1',
        sep=';'
    )

    # Converter preço para número
    df["À vista R$"] = df["À vista R$"].str.replace(",", ".").astype(float)

    # Converter data
    df["Data"] = pd.to_datetime(df["Data"], format="%m/%Y")

    # Ordenar série temporal
    df = df.sort_values("Data")

    # Adiciona à lista de dataframes
    lista_dataframes.append(df)

    # Concatena (mesmo que tenha apenas um arquivo, mantém o padrão do código original)
    arquivo_etanol = pd.concat(lista_dataframes, ignore_index=True)

    # Série temporal
    data = arquivo_etanol["À vista R$"].values

    return arquivo_etanol, data

# Busca os dados de 2014 até 2024
start_year = 2015
end_year = 2025
# Carrega os dados do etanol
df_etanol, data = carregar_dados_etanol()

# Dicionário para armazenar os DataFrames
dfs_series = {}

# Intervalo desejado
inicio = '2015-01-01'
fim = '2025-06-01'

# Cria dataframe no formato padrão de séries temporais
df = (
    df_etanol
    [['Data', 'À vista R$']]
    .rename(columns={
        'Data': 'ds',
        'À vista R$': 'y'
    })
)

# Criar identificador da série
df['unique_id'] = 'etanol'

# Define índice temporal
df = df.set_index('ds')

# Interpolação de possíveis valores faltantes
df['y'] = df['y'].interpolate(method='time')

# Filtrar intervalo de datas
df = df.query("index >= @inicio and index <= @fim")

# Resetar índice
df.reset_index(inplace=True)

# Garantir datetime
df['ds'] = pd.to_datetime(df['ds'])

# Remover duplicatas
df = df.drop_duplicates(subset=['unique_id', 'ds'])

# Salvar no dicionário
dfs_series['etanol'] = df

#Olhando o data frame
df

"""Plotando o gráfico do histórico de preços"""

plt.figure(figsize=(12,5))

plt.plot(df_etanol["Data"], df_etanol["À vista R$"])

plt.title("Preço do Etanol ao longo do tempo")
plt.xlabel("Data")
plt.ylabel("Preço R$")
plt.grid(True)

plt.show()

"""Dividindo a série em treinamento (80%) e teste (20%)"""

# Usar o dataframe para a análise
df_analise = df_etanol.copy()

# Garantir que a coluna de data está em datetime
df_analise["Data"] = pd.to_datetime(df_analise["Data"])

# Ordenar pela data
df_analise = df_analise.sort_values("Data")

# Calcula o índice de corte (80%)
corte_idx = int(len(df_analise) * 0.8)

# Divide treino e teste
df_treino = df_analise.iloc[:corte_idx]
df_teste = df_analise.iloc[corte_idx:]

# Verifica os tamanhos
print(f"Tamanho treino: {len(df_treino)}")
print(f"Tamanho teste: {len(df_teste)}")

# Mostra as datas
print("Treino:", df_treino["Data"].min(), "até", df_treino["Data"].max())
print("Teste:", df_teste["Data"].min(), "até", df_teste["Data"].max())

"""# Gerando os modelos de Machine Learning"""

# cria modelo ingenuo
class Naive(BaseEstimator):
    def fit(self, x, y):
        return self

    def predict(self, X):
        return X['lag1']

# Dicionário de modelos
models = {
    'naive': Naive(),
    'lgbm': lgb.LGBMRegressor(verbosity=-1),
    'lasso': Lasso(),
    'lin_reg': LinearRegression(),
    'ridge': Ridge(),
    'knn': KNeighborsRegressor(),
    'mlp': MLPRegressor(),
    'rf': RandomForestRegressor()
}

# Define os lags
lags = [1, 12]

# Instancia objeto de MLForecast
mlf = MLForecast(
    models=models,
    freq='MS', # Alterado de 'M' para 'MS' para corresponder à frequência de início do mês dos dados
    target_transforms=[Differences([1, 12])],
    lags=lags,
    lag_transforms={
        1: [ExpandingMean()],
        12: [RollingMean(window_size=12)],
    },
    date_features=['month']
)

"""Aplicação da Validação Cruzada
1.   Renomeando colunas
2.   Remoção de duplicatas
3.   Ordenando por Datas


"""

# Garante que a coluna 'ds' está presente como coluna (não como índice)
if df_treino.index.name == 'Data':
    df_treino = df_treino.reset_index()

# Renomeia as colunas para o formato esperado pelo mlforecast
df_treino = df_treino.rename(columns={'Data': 'ds', 'À vista R$': 'y'})

# Adiciona a coluna 'unique_id'
df_treino['unique_id'] = 'etanol'

# Remove duplicatas (se houver)
df_treino = df_treino.drop_duplicates(subset=['unique_id', 'ds'])

# Ordena pela data
df_treino = df_treino.sort_values(by='ds')

# Aplica validação cruzada
crossvalidation_df = mlf.cross_validation(
    df=df_treino,
    h=24,
    n_windows=2,
    refit=False,
    static_features=[]
)

crossvalidation_df

"""Agora plotando cada modelos e a janela(fold do CV) para verificar os seus respectivos comportamentos."""

def plot_cv(df, df_cv, uid, last_n=24*14, models=[]):
    cutoffs = df_cv.query('unique_id == @uid')['cutoff'].unique()

    fig, ax = plt.subplots(nrows=len(cutoffs), ncols=1, figsize=(14, 14),
                           gridspec_kw=dict(hspace=0.8))

    # tratar caso 1 subplot
    if len(cutoffs) == 1:
        axes = [ax]
    else:
        axes = ax.flat

    for cutoff, axi in zip(cutoffs, axes):
        max_date = df_cv.query('(unique_id == @uid) & (cutoff == @cutoff)')['ds'].max()

        # Resetar o índice para garantir que 'ds' seja uma coluna antes de set_index
        df_plot = df.reset_index()

        df_plot.query('unique_id == @uid and ds <= @max_date').set_index('ds')['y'].plot(ax=axi, title=uid)

        for m in models:
            df_cv.query('(unique_id == @uid) & (cutoff == @cutoff)').set_index('ds')[m].plot(ax=axi, label=m)

        axi.legend()

    plt.show()

#Plota
plot_cv(df_treino,crossvalidation_df, 'etanol', models=models)

"""# Métricas de Acurácia
Examina visualmente as previsões pode nos dar alguma ideia de como o modelo está se comportando, mas para avaliar o desempenho, precisamos avaliá-las por meio de métricas. Para isso, usei a biblioteca utilsforecast, que contém muitas métricas úteis e uma função de avaliação.
"""

#métricas utilizadas para a avaliação
metrics=[
    mae,
    mape,
    rmse,
    smape
]

#Função de avaliação da validade cruzada
def evaluate_crossvalidation(crossvalidation_df, metrics,models):
    evaluations = []
    for c in crossvalidation_df['cutoff'].unique():
        df_cv = crossvalidation_df.query('cutoff == @c')
        evaluation = evaluate(
            df = df_cv,
            metrics = metrics,
            models = list(models.keys()),
        )
        evaluations.append(evaluation)
    evaluations = pd.concat(evaluations,ignore_index=True).drop(columns='unique_id')
    evaluations = evaluations.groupby('metric').mean()
    return evaluations.style.background_gradient(cmap='RdYlGn_r',axis=1)

#Verifica as métricas
evaluate_crossvalidation(crossvalidation_df, metrics, models)

"""# Conjunto de teste
Agora vou comparar os dados previsto do conjunto de treinamento no conjunto de teste, de forma a compreender qual modelo melhor realizou a previsão. Adicionei intervalos de confiança para cada previsão.
"""

# Realiza o ajuste com intervalos
mlf.fit(
    df=df_treino,
    prediction_intervals=PredictionIntervals(n_windows=2, h=24)
)

#Define os intervalo e a realiza a previsão
levels = [90,95] #Intervalo de confiança
forecasts = mlf.predict(24,level=levels)
forecasts.head()

# Preparar df_teste para o merge
df_teste_prepared = df_teste.rename(columns={'Data': 'ds', 'À vista R$': 'y'})
df_teste_prepared['unique_id'] = 'etanol'

# Junta os dados do conjunto de teste e a previsão
test = df_teste_prepared.merge(forecasts, on=['unique_id', 'ds'], how='left')
test.info()
test.head()

# Avalia as métricas de erros
evaluate(
    df=test,
    metrics=metrics,
    models=list(models.keys())
).style.background_gradient(cmap='RdYlGn_r',axis=1)

# Avaliação
df_resultado = evaluate(
    df=test,
    metrics=metrics,
    models=list(models.keys())
)

# Caminho local (mesma pasta do notebook)
caminho = 'avaliacao_modelos.csv'

# Exportar
df_resultado.to_csv(caminho, index=False)

print("Arquivo salvo como:", caminho)

"""Construindo as métricas da tabela acima, manualmente. Para assim ter os números arredondados com 4 casas decimais"""

# Criação do DataFrame
df_metrics = pd.DataFrame(
    [
        ['Etanol', 'mae', 5.3097, 0.4046, 1.0747, 1.3756, 0.5311, 0.9633, 0.6462, 0.5636],
        ['Etanol', 'mape', 1.8239, 0.1387, 0.3661, 0.5044, 0.1997, 0.3275, 0.2421, 0.2050],
        ['Etanol', 'rmse', 6.4455, 0.5226, 1.3435, 1.4632, 0.6239, 1.2523, 0.7457, 0.6226],
        ['Etanol', 'smape', 0.7654, 0.0707, 0.2362, 0.1806, 0.0808, 0.2088, 0.0960, 0.0913],
    ],
    columns=[
        'unique_id', 'metric', 'naive', 'lgbm', 'lasso', 'lin_reg', 'ridge', 'knn', 'mlp', 'rf'
    ]
)

# Caminho local
caminho = 'avaliacao_modelos.csv'

# Exportar CSV
df_metrics.to_csv(caminho, index=False)

print("Arquivo salvo como:", caminho)

# Suponha que a tabela de métricas esteja no DataFrame 'df_metrics'
# E que ele tenha as colunas: ['unique_id', 'metric', 'naive', 'lgbm', ..., 'rf']

# Filtra só as colunas de modelos
model_cols = ['naive', 'lgbm', 'lasso', 'lin_reg', 'ridge', 'knn', 'mlp', 'rf']

# Define cores padrão para os modelos
cores = plt.cm.tab10.colors[:len(model_cols)]

# Cria uma figura com subplots por métrica
fig, axes = plt.subplots(2, 2, figsize=(14, 10))
axes = axes.flatten()

# Lista de métricas na ordem esperada
metricas = ['mae', 'mape', 'rmse', 'smape']

for i, metrica in enumerate(metricas):
    ax = axes[i]

    # Seleciona a linha da métrica
    linha = df_metrics[df_metrics['metric'] == metrica]

    # Extrai os valores dos modelos
    valores = linha[model_cols].values.flatten()

    # Cria o gráfico de barras
    bars = ax.bar(model_cols, valores, color=cores)
    #ax.bar(model_cols, valores, color=cores)
    ax.set_title(f'{metrica.upper()} por modelo')
    ax.set_ylabel(metrica.upper())
    ax.set_xticklabels(model_cols, rotation=45)
    ax.bar_label(bars, fmt='%.2f', padding=3)
    ax.grid(axis='y', linestyle='--', alpha=0.5)

plt.suptitle('Comparação de Métricas de Erro entre Modelos', fontsize=16)
plt.tight_layout(rect=[0, 0, 1, 0.96])
plt.show()

"""# Plotando os modelos finais"""

plot_series(
    df_treino,
    test,
    models=list(models.keys()),
    plot_random=False,
    level=None, #antes estava levels no lugar de None
    max_insample_length=24
)

#Plotando o modelo Random Forest com melhores valores de acurácia
plot_series(
    df_treino,
    test,
    models=['rf'],
    plot_random=False,
    level=None, #antes estava levels no lugar de None
    max_insample_length=24
)

# =========================
# DADOS HISTÓRICOS
# =========================

datas_hist = df["ds"]
valores_hist = df["y"]

# =========================
# PREVISÕES
# =========================

datas_prev = forecasts["ds"]

# lista de modelos (todas as colunas exceto id e data)
modelos = [
    col for col in forecasts.columns
    if col not in ["unique_id", "ds"]
    and "-lo-" not in col
    and "-hi-" not in col
]

# =========================
# PLOT
# =========================

plt.figure(figsize=(16,7))

# Histórico
plt.plot(datas_hist, valores_hist,
         label="Histórico", linewidth=3, color='black')

# Plot de cada modelo
for modelo in modelos:
    plt.plot(datas_prev, forecasts[modelo],
             linestyle='-', linewidth=2, label=modelo)

# Linha separadora
#plt.axvline(x=datas_hist.max(), color='black', linestyle='--', linewidth=1.5)

# Formatação eixo X
plt.gca().xaxis.set_major_locator(mdates.YearLocator())
plt.gca().xaxis.set_major_formatter(mdates.DateFormatter('%Y'))

plt.title("Comparação de Previsões - Modelos MLForecast", fontsize=14)
plt.xlabel("Ano")
plt.ylabel("Preço (R$)")

plt.ylim(0)
plt.legend(loc='best', ncol=2)
plt.grid(True, alpha=0.3)

plt.tight_layout()
plt.show()

# Histórico
plt.figure(figsize=(14,6))
plt.plot(df["ds"], df["y"], label="Histórico", linewidth=2,color='black')

cores = {
    'rf': 'red',
    'mlp': 'blue',
    'ridge': 'green'
}

top_models = ['rf', 'mlp', 'ridge'] # Define top_models here

for modelo in top_models:
    plt.plot(forecasts["ds"], forecasts[modelo], # Corrected 'forecast' to 'forecasts'
             linestyle='-',
             linewidth=2,
             color=cores[modelo],
             label=modelo.upper())

# Formatação eixo X
plt.gca().xaxis.set_major_locator(mdates.YearLocator())
plt.gca().xaxis.set_major_formatter(mdates.DateFormatter('%Y'))

plt.title("Previsão do Preço do Etanol - 3 melhores modelos")
plt.xlabel("Ano")
plt.ylabel("Preço (R$)")

plt.ylim(0)

plt.legend(loc='upper left', ncol=2)
plt.grid(True, alpha=0.3)
plt.tight_layout()

plt.show()