# -*- coding: utf-8 -*-
"""SARIMA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16R8cc7TmRiOMXjIoXYOP-bmwraX63mP6
"""

!pip install numpy
!pip install scipy
!pip install scikit-learn
!pip install cython
!pip install pmdarima

# Commented out IPython magic to ensure Python compatibility.
import os
import warnings
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
import datetime as dt
import math

from pandas.plotting import autocorrelation_plot
from pmdarima import auto_arima
from statsmodels.tsa.statespace.sarimax import SARIMAX
from sklearn.preprocessing import MinMaxScaler
#from common.utils import load_data, mape
from IPython.display import Image

# %matplotlib inline
pd.options.display.float_format = '{:,.2f}'.format
np.set_printoptions(precision=2)
warnings.filterwarnings("ignore") # specify to ignore warning messages

# Conexão entre o Google Colab e o Google Drive
from google.colab import drive
drive.mount('/content/drive')

"""Fazer o upload do arquivo disponibilizado:

> base_de_dados_etanol.csv


"""

from google.colab import files
uploaded = files.upload()

# Cria a função para carregar os dados do etanol
def download_ons(start_year=None, end_year=None):

    # Lê o arquivo CSV
    df = pd.read_csv(
        "base_de_dados_etanol.csv",
        encoding='latin-1',
        sep=';'
    )

    # Converter preço para número
    df["À vista R$"] = df["À vista R$"].str.replace(",", ".").astype(float)

    # Converter data
    df["Data"] = pd.to_datetime(df["Data"], format="%m/%Y")

    # Ordenar a série temporal
    df = df.sort_values("Data")

    # Série temporal
    data = df["À vista R$"].values

    return df

# Busca os dados de 2015 até 2025
start_year = 2015
end_year = 2025
df_ons = download_ons(start_year, end_year)

# Olhando os dados
df_ons

# Criando uma cópia do data frame original, para um data frame df.
df = df_ons.copy()

# Usar o dataframe do etanol para a análise
df_analise = df.copy()

# Garantir que a coluna Data está em datetime
df_analise["Data"] = pd.to_datetime(df_analise["Data"])

# Ordenar pela data
df_analise = df_analise.sort_values("Data")

# Calcular índice de corte (80% treino)
corte_idx = int(len(df_analise) * 0.8)

# Dividir treino e teste
df_treino = df_analise.iloc[:corte_idx]
df_teste = df_analise.iloc[corte_idx:]

# Verificar tamanhos
print(f"Tamanho treino: {len(df_treino)}")
print(f"Tamanho teste: {len(df_teste)}")

# Mostrar período de cada conjunto
print("Treino:", df_treino["Data"].min(), "até", df_treino["Data"].max())
print("Teste:", df_teste["Data"].min(), "até", df_teste["Data"].max())

# Plot dos dados de treino e teste
plt.figure(figsize=(15, 8))

plt.plot(df_treino['Data'], df_treino['À vista R$'], label='Treino')
plt.plot(df_teste['Data'], df_teste['À vista R$'], label='Teste')

plt.xlabel('Data', fontsize=12)
plt.ylabel('Preço do Etanol (R$)', fontsize=12)

plt.title('Divisão Treino vs Teste - Série de Preço do Etanol')

plt.legend()
plt.grid(True)

plt.show()

# Colocando a data no índice de treino e teste
df_treino = df_treino.set_index('Data')
df_teste = df_teste.set_index('Data')

#vendo as dimensões da base de dados de treino e teste
print('Training data shape: ', df_treino.shape)
print('Test data shape: ', df_teste.shape)

"""#Implementar SARIMA
É hora de implementar o SARIMA! Agora você usará a statsmodels biblioteca que instalou anteriormente.

Agora você precisa seguir vários passos

Defina o modelo chamando SARIMAX()e passando os parâmetros do modelo: parâmetros p, d e q, e parâmetros P, D e Q.
Prepare o modelo para os dados de treinamento chamando a função fit().
Faça previsões chamando a forecast()função e especificando o número de etapas (o horizon) a serem previstas. Para que servem todos esses parâmetros? Em um modelo ARIMA, existem 3 parâmetros usados para ajudar a modelar os principais aspectos de uma série temporal: sazonalidade, tendência e ruído. Esses parâmetros são:

p: o parâmetro associado ao aspecto autorregressivo do modelo, que incorpora valores passados . d: o parâmetro associado à parte integrada do modelo, que afeta a quantidade de diferenciação (lembra da diferenciação?) a ser aplicada a uma série temporal. q: o parâmetro associado à parte da média móvel do modelo.
"""

#Comece definindo o seu horizonte preferido. Vamos tentar 3 horas:
HORIZON = 24
print('Forecasting horizon:', HORIZON, 'months')

# Usar o dataframe do etanol para a análise
df_analise = df.copy()

# Garantir que a coluna Data está em datetime
df_analise["Data"] = pd.to_datetime(df_analise["Data"])

# Ordenar pela data
df_analise = df_analise.sort_values("Data")

# Calcular índice de corte (80% treino)
corte_idx = int(len(df_analise) * 0.8)

# Dividir treino e teste
df_treino = df_analise.iloc[:corte_idx]
df_teste = df_analise.iloc[corte_idx:]

# Verificar tamanhos
print(f"Tamanho treino: {len(df_treino)}")
print(f"Tamanho teste: {len(df_teste)}")

# Mostrar período de cada conjunto
print("Treino:", df_treino["Data"].min(), "até", df_treino["Data"].max())
print("Teste:", df_teste["Data"].min(), "até", df_teste["Data"].max())

import itertools
import pandas as pd
from statsmodels.tsa.statespace.sarimax import SARIMAX

# Série de treino
serie = df_treino["À vista R$"]

# Intervalos de parâmetros
p = d = q = range(0, 3)
P = D = Q = range(0, 2)

# Sazonalidade mensal
m = 12

# Combinações possíveis
parametros = list(itertools.product(p, d, q))
parametros_sazonais = list(itertools.product(P, D, Q))

resultados = []

print("Testando modelos...")

for param in parametros:
    for param_sazonal in parametros_sazonais:
        try:
            modelo = SARIMAX(
                serie,
                order=param,
                seasonal_order=(param_sazonal[0], param_sazonal[1], param_sazonal[2], m),
                enforce_stationarity=False,
                enforce_invertibility=False
            )

            resultado = modelo.fit(disp=False)

            resultados.append({
                "order": param,
                "seasonal_order": (param_sazonal[0], param_sazonal[1], param_sazonal[2], m),
                "AIC": resultado.aic,
                "BIC": resultado.bic
            })

        except:
            continue

# Criar DataFrame com resultados
df_resultados = pd.DataFrame(resultados)

# Ordenar pelos melhores modelos
df_resultados = df_resultados.sort_values("AIC")

print(df_resultados.head(10))

modelo_final = SARIMAX(
    serie,
    order=(0,1,0),
    seasonal_order=(0,0,0,12)
).fit()

print(modelo_final.summary())

print(modelo_final.aic)
print(modelo_final.bic)

"""#Previsão
Aqui faz a previsão dos dados
"""

# Número de períodos a prever
n_periods = len(df_teste)

# Faz a previsão
forecast = modelo_final.forecast(steps=n_periods)

# Cria série com mesmo índice do teste
forecast_index = df_teste.index
previsao = pd.Series(forecast, index=forecast_index)

"""# gráfico
Aqui foi feito uma correção no gráfico para unir a série de treino com a série de teste
"""

# Cria uma série contínua com todos os dados reais usando as datas corretas como índice
# Junta os dois dataframes de treino e de teste para serem plotadas continuamente
serie_real_completa = pd.concat([df_treino['À vista R$'], df_teste['À vista R$']])

# Garante que o índice da previsão está em datetime
previsao.index = df_teste.index

# Plotação dos dados
plt.figure(figsize=(15, 6))

# Dados reais completos (treino + teste)
plt.plot(serie_real_completa.index, serie_real_completa, label='y real (Treino)', color='blue')
plt.plot(df_teste.index, df_teste['À vista R$'], label='Real (Teste)', color='orange')

# Previsões apenas no período de teste
plt.plot(previsao.index, previsao, label='Previsão', color='green', linestyle='--')

plt.title('Previsão com SARIMAX(0, 1, 0)(0, 0, 0)')
plt.xlabel('Data')
plt.ylabel('Preço (R$)')
plt.legend()
plt.grid(True)
plt.show()

# Compare as previsões com a carga real:

# Create a DataFrame para comparar valores atuais com previsão
eval_df = pd.DataFrame({
    'atual': df_teste['À vista R$'],
    'previsão': previsao
})

eval_df.head()

"""# Métricas de Desempenho (MAE, MAPE, RMSE e sMAPE)"""

from sklearn.metrics import mean_absolute_error, mean_squared_error

# 3. Valores reais do teste
reais = df_teste['À vista R$'].values

# 4. Calcula as métricas
previsoes = previsao.values # Use the defined 'previsao' variable

# MAE
mae = mean_absolute_error(reais, previsoes)

# RMSE
rmse = np.sqrt(mean_squared_error(reais, previsoes))

# MAPE
mape = np.mean(np.abs((reais - previsoes) / reais)) * 100

# sMAPE
smape = np.mean(2 * np.abs(previsoes - reais) / (np.abs(reais) + np.abs(previsoes))) * 100

# 5. Exibe os resultados
print(f"MAE: {mae:.2f}")
print(f"RMSE: {rmse:.2f}")
print(f"MAPE: {mape:.2f}%")
print(f"sMAPE: {smape:.2f}%")